CREATE DATABASE IF NOT EXISTS fiber;

CREATE TABLE fiber.user (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    full_name VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(50)
);